# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: de553be478169ebba1814590da5080533af738404ae3cb8e1c99ecff1b50388038f689950aea1bb813b13834cbdf3916702648e0ec09f7e5f93d88e1a29086e8

test:
  secret_key_base: 3a5370e59edaef652b575b3a959856b053991b7bdeaf639234cf75180ae699901de4f202d934acccac7fa6bc71da82447757317fc0b7d04ec2572963e062bd33

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
